### ISSUE TITLE
您好,支持DZ3.4版本吗

### ISSUE THREAD

**Issue by tudou88** [scriptscat/dz_markdown#3]
我看安装上去没有反应呢,能否兼容下

**Comment by CodFrm** [comment]
https://bbs.tampermonkey.net.cn/

支持的，可以参考本站

**Comment by tudou88** [comment]
好的 大佬 感谢您

**Comment by CodFrm** [comment]
不能直接安装，还需要在src中安装编辑器的相关依赖

我这里直接打个包给你吧

[归档.zip](https://github.com/scriptscat/dz_markdown/files/10100309/default.zip)

**Comment by tudou88** [comment]
谢谢大佬
