### ISSUE TITLE
dz3.5 20230726 上发帖时使用该插件上传图片，点击保存时报错~

### ISSUE THREAD

**Issue by 16cm** [scriptscat/dz_markdown#4]
dz3.5 20230726 上发帖时使用该插件上传图片，点击保存时报错~

![image](https://github.com/scriptscat/dz_markdown/assets/20642702/7d2fce62-6d56-4e78-98d1-331d50b07d1a)

**Comment by 16cm** [comment]
提交发布帖子时，所带的参数 attachnew[15113] 设置为空字符提交到服务器了，导致最新的dz处理这个时出错

dz出错点：`source/function/function_post.php` 204行：
`$update['readperm'] = $_G['group']['allowsetattachperm'] ? $attach['readperm'] : 0;`

解决：上传 attachnew 参数时，不要只 attachnew[1314] 而是
- attachnew[1314][description]
- attachnew[1314][readperm]
- attachnew[1314][price]

`source/plugin/codfrm_markdown/dist/editor.js`  文件的这个位置： `document.querySelector("#postbox").append(r),`

> 注意：传递的 attachnew 参数是附件的描述、用户组和价格

但是有个新问题，如果只上传一图片，那么发帖后，显示2张图片。。。

希望能够改进这个插件，蟹蟹~

**Comment by CodFrm** [comment]
<img width="1438" alt="image" src="https://github.com/scriptscat/dz_markdown/assets/22783163/3d3625fa-64c1-46d6-9f62-f8891ebb0cb3">

我这里本地调试没有复现，怎么出现的？

**Comment by 16cm** [comment]
> <img alt="image" width="1438" src="https://user-images.githubusercontent.com/22783163/258624140-3d3625fa-64c1-46d6-9f62-f8891ebb0cb3.png">
> 我这里本地调试没有复现，怎么出现的？

额，关于上传1张图片显示时出现两张图片的问题，是我用另一个markdown插件渲染的结果导致的；你的插件没问题是因为做了处理了：https://github.com/scriptscat/dz_markdown/blob/6ce1e681c003f40b0f6888b861cc1a7e81fa22c9/src/markdown.class.php#L136

**Comment by CodFrm** [comment]
是的，我处理了这个附加附件的问题

另外报错我这里没有复现

**Comment by 16cm** [comment]
> 是的，我处理了这个附加附件的问题
> 
> 另外报错我这里没有复现

我使用的是PHP8.x + Dz3.5，检查下你是否使用PHP7.x而导致没报错问题

**Comment by CodFrm** [comment]
使用php8确实报错了

已修复
