### ISSUE TITLE
【提问】请问没有 docker 环境可以使用这个插件吗？

### ISSUE THREAD

**Issue by xdingya** [scriptscat/dz_markdown#5]
新人开发者一枚勿喷 QWQ
我将 main 分支下的 src 文件下的内容放到 DiscuzX3.5 的插件目录下面的 codfrm_markdown 目录 但启用插件后功能无法使用，请问是什么原因

**Comment by CodFrm** [comment]
和docker无关，使用docker只是方便开发

另外需要使用yarn和composer安装包才可以使用

```
cd src
yarn
composer installl
```

**Comment by xdingya** [comment]
README.md 里面的应该是
composer install 吧？不是installl

**Comment by xdingya** [comment]
我好像还是不会使用🤣

**Comment by CodFrm** [comment]
@xdingya 是的，install，我打错了
