### ISSUE TITLE
依赖打包请求

### ISSUE THREAD

**Issue by taozhiyu** [scriptscat/dz_markdown#6]
看到 #5 中提到需要安装依赖，能否打包相关依赖打包一个 开箱即用 的版本（类似于nodejs中的dist）

最好添加配置页，上传到dz开发者平台

**Comment by CodFrm** [comment]
dz开发者平台我至今还没明白咋上传的，如果有懂哥可以协助一下

关于依赖，我现在手动打包一个吧，后续如果需求多的话，可以写一个action

[归档.zip](https://github.com/scriptscat/dz_markdown/files/12604476/default.zip)

**Comment by CodFrm** [comment]
已上架
https://addon.dismall.com/plugins/codfrm_markdown.html
