### ISSUE TITLE
12月新出的3.5正式版亲测好像没效果

### ISSUE THREAD

**Issue by szhiku** [scriptscat/dz_markdown#8]
按步骤安装了，插件也加载了，但是编辑器还是原来的

**Comment by CodFrm** [comment]
是这个版本？Discuz_X3.5_SC_UTF8_20231001.zip

12份好像没有，官网没有 https://www.discuz.vip/download.html https://gitee.com/Discuz/DiscuzX/releases

只看见打了个tag

**Comment by szhiku** [comment]
您的邮件我已收到

**Comment by CodFrm** [comment]
等出release了再看看

**Comment by szhiku** [comment]
https://www.dismall.com/thread-14660-1-1.html
在社区

**Comment by szhiku** [comment]
我在想要不先退回Discuz_X3.5_SC_UTF8_20231001.zip

**Comment by CodFrm** [comment]
先回退呗，最近还没时间来处理这问题，等下个release版本看看

**Comment by CodFrm** [comment]
目前没发现问题 20231221
